name: EditorConfig checker

on:
  push:
    branches: ['Master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: cd ./Implementation/Source/
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - run: npm i
    - run: npm test